modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "ismah"
version = "${version}"
displayName = "I See My Armored Hand"
authors = "RazorPlay01"
description = '''
Tired of not seeing your equipped armor in first person? I See My Armored Hand adds a visual of your arm armor when looking down, providing increased immersion and a better sense of your character s protection.
'''
logoFile = "icon.png"

[[dependencies.ismah]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.ismah]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1]"
ordering = "NONE"
side = "CLIENT"
